name: Continuous Integration
run-name: Continuous Integration
on:
  push:
    branches:
      - matrix
  pull_request:
    branches:
      - matrix
concurrency:
  group: ci
  cancel-in-progress: true
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Security
        run: echo 'Security Mock'
  dependency:
    runs-on: ubuntu-latest
    steps:
      - name: Dependency
        run: echo 'Dependency Mock'
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
        run: npm ci
        run: npm run build
        run: npm run lint
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Analysis
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SONAR_TOKEN: ${{secrets.SONARCLOUD}}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=ximatriarx
            -Dsonar.projectKey=XiMatriarx_typescript
            -Dsonar.sources=.
            -Dsonar.tests=test
            -Dsonar.javascript.coverage.reportPaths=coverage/clover.xml
            -Dsonar.verbose=true
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
        run: npm ci
        run: npm run build
        run: npm test
