name: Cron
run-name: Cron
on:
  schedule:
    - cron: '0 4 * * *'
concurrency:
  group: cron
  cancel-in-progress: true
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Cron
        run: echo "Cron Mock"
