name: Release
run-name: Release
on:
  push:
    tags:
      - v*
  pull_request:
    tags:
      - v*
concurrency:
  group: release
  cancel-in-progress: true
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Security
        run: echo 'Security Mock'
  dependency:
    runs-on: ubuntu-latest
    steps:
      - name: Dependency
        run: echo 'Dependency Mock'
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Analysis
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SONAR_TOKEN: ${{secrets.SONARCLOUD}}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=ximatriarx
            -Dsonar.projectKey=XiMatriarx_typescript
            -Dsonar.sources=src
            -Dsonar.tests=test
            -Dsonar.javascript.coverage.reportPaths=coverage/lcov.info
            -Dsonar.verbose=true
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
  release:
    needs: [security, dependency, analysis, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@XiMatriarx'
          always-auth: true
      - name: Release
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM}}
